In [22]:
import numpy as np

arr1 = np.array([1,3,3,7])
arr2 = np.zeros((3,3))
arr3 = np.ones((2,2))
arr4 = np.arange(2,65,2)
print(arr3.shape)
print(arr2.dtype)
print(arr4[4])
print(arr1[2:4])

a = np.array([[1,2,3],[1,2,3],[1,2,3]])
b = np.array([[3,2,1],[3,2,1],[3,2,1]])
print(a+b)
print(a*b)

m = np.arange(100)
print(m.mean)

(2, 2)
float64
10
[3 7]
[[4 4 4]
 [4 4 4]
 [4 4 4]]
[[3 4 3]
 [3 4 3]
 [3 4 3]]
<built-in method mean of numpy.ndarray object at 0x4efa928>
